frontend/src/components/OnboardingDialog.tsx
frontend/src/pages/Settings.tsx

Allow reset of telemetry dialog to make testing easier
Update copy of onboarding dialog to "continue" as it's not the final onboarding step

Update settings (vibe-kanban)

---

frontend/src/components/layout/navbar.tsx

https://github.com/BloopAI/vibe-kanban/issues
Next to docs, if the user needs support

Add a link to GitHub issues (vibe-kanban)

---

frontend/src/App.tsx
frontend/src/components/GitHubLoginDialog.tsx
frontend/src/components/config-provider.tsx
frontend/src/components/context/TaskDetailsContextProvider.tsx
frontend/src/components/projects/project-detail.tsx
frontend/src/components/projects/project-form.tsx
frontend/src/components/projects/project-list.tsx
frontend/src/components/tasks/DeleteFileConfirmationDialog.tsx
frontend/src/components/tasks/TaskActivityHistory.tsx
frontend/src/components/tasks/TaskDetails/Conversation.tsx
frontend/src/components/tasks/TaskDetails/DiffCard.tsx
frontend/src/components/tasks/TaskDetails/DiffTab.tsx
frontend/src/components/tasks/TaskDetails/LogsTab.tsx
frontend/src/components/tasks/TaskDetails/LogsTab/Conversation.tsx
frontend/src/components/tasks/TaskDetails/LogsTab/NormalizedConversationViewer.tsx
frontend/src/components/tasks/TaskDetails/LogsTab/SetupScriptRunning.tsx
frontend/src/components/tasks/TaskDetails/NormalizedConversationViewer.tsx
frontend/src/components/tasks/TaskDetailsPanel.tsx
frontend/src/components/tasks/TaskDetailsToolbar.tsx
frontend/src/components/tasks/TaskFollowUpSection.tsx
frontend/src/components/tasks/Toolbar/CreateAttempt.tsx
frontend/src/components/tasks/Toolbar/CreatePRDialog.tsx
frontend/src/components/tasks/Toolbar/CurrentAttempt.tsx
frontend/src/components/ui/file-search-textarea.tsx
frontend/src/components/ui/folder-picker.tsx
frontend/src/components/ui/loader.tsx
frontend/src/lib/api.ts
frontend/src/pages/McpServers.tsx
frontend/src/pages/project-tasks.tsx
shared/types.ts

- all api calls are defined in one file - `lib/api.ts` and all components use it instead of custom fetch and makeRequest calls
- use the same loader everywhere
- minor fixes

Normalise API calls on FE

---

backend/src/bin/generate_types.rs
backend/src/executor.rs
backend/src/executors/ccr.rs
backend/src/executors/claude.rs
backend/src/executors/mod.rs
backend/src/services/process_service.rs
shared/types.ts

Implement Claude Code Router executor.
resolves #182.

feat: Claude Code Router (CCR) executor

---

frontend/src/components/ui/auto-expanding-textarea.tsx

frontend/src/components/ui/auto-expanding-textarea.tsx

Can't scroll expanding textarea (vibe-kanban)

---

frontend/src/lib/api.ts

https://github.com/BloopAI/vibe-kanban/issues/212

Fix open project in editor request

---

frontend/src/pages/project-tasks.tsx

Add templates from kanban dropdown, also means templates button is shown when there are 0 templates, increasing adoption of the feature

Add task templates from kanban

---

backend/src/main.rs

https://github.com/BloopAI/vibe-kanban/issues/237

chore: lower auto-assign port log level

---

backend/src/executors/claude.rs

Replace bugged hooks with wrapper to kill when result for exit_plan_mode is detected.

Fixes possible duplicate plans in plan mode

---

backend/Cargo.toml
backend/src/bin/generate_types.rs
backend/src/executor.rs
backend/src/executors/mod.rs
backend/src/executors/sst_opencode.rs
backend/src/executors/sst_opencode/filter.rs
backend/src/executors/sst_opencode/tools.rs
backend/src/services/process_service.rs
backend/src/utils.rs
backend/src/utils/path.rs
frontend/src/pages/McpServers.tsx
shared/types.ts

sst Opencode

---

frontend/src/components/tasks/Toolbar/CurrentAttempt.tsx

Should have a tooltip to remind user to add a dev server script in project settings
frontend/src/components/tasks/TaskDetailsToolbar.tsx

Dev server disabled tooltip (vibe-kanban)

---

backend/Cargo.toml
backend/src/executor.rs
backend/src/models/config.rs
npx-cli/package.json
package-lock.json
package.json

fix: config migration and CI windows build fixes for opencode

---

backend/src/executor.rs
backend/src/executors/amp.rs
backend/src/executors/ccr.rs
backend/src/executors/charm_opencode.rs
backend/src/executors/claude.rs
backend/src/executors/gemini.rs
backend/src/executors/mod.rs
backend/src/executors/sst_opencode.rs
backend/src/services/process_service.rs

- Now `Executor` implements both `spawn` and `spawn_followup`
- Removed `FolloupExecutors`

refactor: consolidate `Executor` and `FollowUpExecutor` structs

---

frontend/src/components/tasks/TaskDetails/LogsTab/Conversation.tsx
frontend/src/components/tasks/TaskDetails/LogsTab/NormalizedConversationViewer.tsx
frontend/src/hooks/useNormalizedConversation.ts

Hide streamed logs as we do with static ones when there are over 100 of them, add a button to load previous logs

Improve streamed logs rendering

---

backend/src/routes/stream.rs

Implement ?since_batch_id for non-gemini executors

Debug stream

---

backend/src/execution_monitor.rs

**Key Location**: `/backend/src/services/process_service.rs`
The `CleanupScriptExecutor` is instantiated and executed in:
- **Line 817-823**: In `execute_process()` method, when handling `ExecutorType::CleanupScript(script)`
- **Line 679-700**: In `start_cleanup_script()` method
- **Line 22-60**: In `run_cleanup_script_if_configured()` method (main entry point)
**Key Trigger Point**: The cleanup script is automatically triggered after coding agent completion in the execution monitor at `/backend/src/execution_monitor.rs:966-983`.
**Central Orchestrator**: `/backend/src/services/process_service.rs` - `ProcessService`
**Key Methods**:
- `start_execution()` - Main entry point for task execution
- `start_process_execution()` - Unified process spawning
- `execute_process()` - Process-specific …

Execute Plan: Auto commit changes after cleanup script (vibe-kanban)

---

backend/src/utils/worktree_manager.rs

fix worktree creation for windows

---

backend/src/bin/generate_types.rs
backend/src/executor.rs
backend/src/executors/claude.rs
shared/types.ts

Display claude-code executor as Claude Code rather than Claude

---

Dockerfile

Dockerfile - fix FE build script

---

backend/src/bin/generate_types.rs
backend/src/models/config.rs
backend/src/routes/config.rs
backend/src/routes/health.rs
frontend/src/components/projects/project-form-fields.tsx
frontend/src/hooks/use-system-info.ts
frontend/src/utils/script-placeholders.ts
package.json
shared/types.ts

Cross-platform project script UI placeholders

---

README.md

If not already mentioned, cargo install cargo-watch
And sqlx cli

Add dependencies to readme (vibe-kanban)

---

crates/server/src/routes/task_attempts.rs
crates/services/src/services/container.rs

Run cleanup scripts after each coding task completes

refactor: cleanup scripts

---

crates/local-deployment/src/container.rs
crates/local-deployment/src/lib.rs
crates/services/src/services/analytics.rs
crates/services/src/services/container.rs
crates/utils/src/lib.rs

Only play sound notifications when a cleanup script has finished, or a coding agent with no cleanup script has finished.

refactor: conditional notification

---

crates/db/src/models/execution_process.rs
crates/local-deployment/src/container.rs
crates/server/src/routes/task_attempts.rs
crates/services/src/services/container.rs
frontend/src/components/context/TaskDetailsContextProvider.tsx
frontend/src/lib/api.ts
shared/types.ts

- Cleanup api.ts
- Re-add /api/task-attempts/{id}/stop endpoint

Re-add stop task attempt endpoint

---

frontend/src/components/tasks/TaskDetails/DiffTab.tsx

Please surround this in try/catch as sometimes I get issues that are hard to predict like:
Error: Expected hunk header but reached end of diff
at bK.parseHunk (index.mjs:890:19)
at bK.parse (index.mjs:983:35)
at index.mjs:2147:101
at Array.map (<anonymous>)
at Qd.cP (index.mjs:2147:76)
at Qd.initRaw (index.mjs:1830:82)
at DiffTab.tsx:35:14
at DiffTab.tsx:43:24
at Array.map (<anonymous>)
at DiffTab.tsx:43:8
at Object.zw [as useMemo] (react-dom.production.min.js:172:119)
at Be.useMemo (react.production.min.js:26:48)
at $Z (DiffTab.tsx:39:21)

DiffTab.tsx should be safe (vibe-kanban)

---

crates/server/src/routes/task_attempts.rs
frontend/src/components/DiffCard.tsx
frontend/src/lib/api.ts

In frontend/src/components/DiffCard.tsx
There are examples of this button in other places

Add open in IDE button next to file path (vibe-kanban)

---

crates/executors/src/executors/amp.rs
crates/executors/src/logs/utils/entry_index.rs
crates/executors/src/logs/utils/patch.rs
crates/local-deployment/src/container.rs
crates/services/src/services/config/versions/v3.rs
crates/services/src/services/container.rs
crates/utils/src/msg_store.rs
frontend/src/hooks/useEventSourceManager.ts

- Improves speed of Amp logs
- Fixes bug with delete JSON patches in stream
- Fixes bug where only a limited number of history normalized logs were shown

Improve normalized logs

---

crates/db/.sqlx/query-283a8ef6493346c9ee3bf649e977849eb361d801cdfc8180a8f082269a6bd649.json
crates/db/.sqlx/query-59d178b298ba60d490a9081a40064a5acb06fecbc0b164c0de2fe502d02b13a7.json
crates/db/.sqlx/query-71c7befa63391ca211eb69036ff0e4aabe92932fd8bb7ba8c52b2ae8bf411ac8.json
crates/db/.sqlx/query-72769cc30de13bb250687b26609ee95660cb4b716615406ecb6f45c4562c3f97.json
crates/db/.sqlx/query-821192d8d8a8fba8ce0f144a32e7e500aaa2b6e527b7e7f082a1c73b1f9f9eb8.json
crates/db/.sqlx/query-b95cb59154da69213dea2ded3646d2df2f68293be211cc4f9db0582ea691efee.json
crates/db/migrations/20250811000000_add_copy_files_to_projects.sql
crates/db/src/models/project.rs
crates/local-deployment/src/container.rs
crates/server/src/routes/projects.rs
crates/services/src/services/container.rs
frontend/src/components/projects/copy-files-field.tsx
frontend/src/components/projects/project-form-fields.tsx
frontend/src/components/projects/project-form.tsx
frontend/src/components/ui/multi-file-search-textarea.tsx
frontend/src/lib/api.ts
shared/types.ts

https://github.com/BloopAI/vibe-kanban/issues/444
This PR adds a new optional copy_files
field to projects that allows specifying
files to be automatically copied from the
original project directory to the git
worktree when a task is executed.
When Vibe Kanban creates a git worktree
for task execution, certain
environment-specific files (like .env,
local configuration files, secrets) are
not tracked in git and therefore don't
exist in the worktree. This requires
manual copying of these files or causes
task execution failures.
- Added copy_files field to the projects
table and model
- Implemented automatic file copying logic
in the container service
- Added UI field in project form to
specify comma-separated list of files to
copy
- Database: Added migration to add
copy_files column to …

add copy files setting

---

npx-cli/bin/cli.js

Fix MCP server

---

crates/executors/src/executors/mod.rs
crates/executors/src/profile.rs
frontend/src/components/GitHubLoginDialog.tsx

frontend/src/components/GitHubLoginDialog.tsx

Fix darkmode styles on github login (vibe-kanban)

---

frontend/package-lock.json
frontend/package.json
frontend/src/components/ui/json-editor.tsx
frontend/src/main.tsx
frontend/src/pages/McpServers.tsx
frontend/src/pages/Settings.tsx
pnpm-lock.yaml

There are several places in the UI where the user can edit JSON. Currently we have raw text input, but this would be better if it was a JSON editor.
Please use @uiw/react-codemirror
The places to use:
- Settings page, Agent Profiles section
- MCP Servers page, MCP Server Configuration
Please plan how to make this change, check your plan using the oracle, confirm with me before making changes

Use codemirror for JSON editing (vibe-kanban)

---

crates/utils/src/path.rs
frontend/src/components/tasks/BranchSelector.tsx

frontend/src/components/tasks/BranchSelector.tsx

Can't navigate using keyboard when searching branch (vibe-kanban)

---

frontend/src/App.tsx
frontend/src/main.tsx
frontend/src/vscode/ContextMenu.tsx
frontend/src/vscode/bridge.ts

- Forward key-events to vscode when vibe-kanban is hosted in an iframe.
- Create a context-menu for copy/paste operation in iframe mode.

VScode extension key events and context menu

---

crates/server/src/routes/task_attempts.rs
crates/server/src/routes/tasks.rs
crates/services/src/services/git.rs
frontend/src/components/tasks/Toolbar/CurrentAttempt.tsx
frontend/src/lib/api.ts
package-lock.json
shared/types.ts

Enable pushing new changes to an exisitng vk pr.

Update pr after creation

---

frontend/src/components/tasks/TaskDetails/ProcessCard.tsx
frontend/src/components/tasks/TaskDetails/ProcessLogsViewer.tsx
frontend/src/components/tasks/TaskDetails/ProcessesTab.tsx
frontend/src/hooks/useLogStream.ts

When I click on a process I currently see the "process details". It should also be possible to see the logs for that process.
Please plan how to do this, review your plan using the oracle, confirm with me before making changes

It should be possible to view logs in the processes tab (vibe-kanban)

---

crates/db/Cargo.toml
crates/deployment/Cargo.toml
crates/executors/Cargo.toml
crates/local-deployment/Cargo.toml
crates/server/Cargo.toml
crates/services/Cargo.toml
crates/utils/Cargo.toml
npx-cli/package.json
package-lock.json
package.json

This reverts commit a64a3a00d0562e928ece1f6f6d3607183a686938.

Revert "chore: bump version to 0.0.63"

---

crates/services/src/services/config/versions/v2.rs
frontend/src/components/tasks/Toolbar/CurrentAttempt.tsx
shared/types.ts

Add Xcode as editor

---

frontend/src/components/tasks/TaskDetails/ProcessLogsViewer.tsx
frontend/src/components/tasks/TaskDetails/ProcessesTab.tsx
frontend/src/components/tasks/TaskDetailsPanel.tsx
frontend/src/components/tasks/Toolbar/CurrentAttempt.tsx
frontend/src/contexts/ProcessSelectionContext.tsx
frontend/src/contexts/TabNavigationContext.tsx

Make it easier to view the dev server logs, when a user runs a dev server (by clicking 'dev server' button) a new button should be displayed next to it to open the logs. This will open the processes tab at the relevant execution process so the user can see raw logs.

Dev server logs (vibe-kanban)

---

test.txt

Test (vibe-kanban)

---

crates/executors/default_profiles.json
crates/executors/src/command.rs
crates/executors/src/executors/amp.rs
crates/executors/src/executors/claude.rs
crates/executors/src/executors/codex.rs
crates/executors/src/executors/cursor.rs
crates/executors/src/executors/gemini.rs
crates/executors/src/executors/opencode.rs
crates/executors/src/executors/qwen.rs
crates/server/src/bin/generate_types.rs
shared/types.ts

CmdOverride consistency
Added some more common CLI args for executors

Refactor command builders

---

crates/server/src/routes/execution_processes.rs
crates/server/src/routes/tasks.rs
crates/services/src/services/events.rs
crates/services/tests/git_ops_safety.rs
frontend/src/hooks/useProjectTasks.ts
frontend/src/pages/project-tasks.tsx
shared/types.ts

Implement streaming for project tasks

---

crates/db/.sqlx/query-69234edbfb4ec9fad3e3411fccae611558bc1940dcec18221657bd3a3ad45aee.json
crates/db/src/models/project.rs
crates/deployment/src/lib.rs
crates/local-deployment/src/lib.rs
crates/server/src/bin/generate_types.rs
crates/server/src/main.rs
crates/server/src/routes/projects.rs
crates/services/Cargo.toml
crates/services/src/services/file_ranker.rs
crates/services/src/services/file_search_cache.rs
crates/services/src/services/mod.rs
frontend/src/components/ui/multi-file-search-textarea.tsx
frontend/src/lib/api.ts
shared/types.ts

Implement file search performance optimizations to eliminate cold start delays and provide instant search responses.
The system's caching strategy should be enhanced such that file indexes and git history statistics are pre-built during server startup for the top 3 most actively used projects (determined by recent task activity).
Search requests should use a non-blocking approach that returns cached results in under 5ms when available, or falls back to filesystem traversal in 40-60ms when cache is unavailable, while triggering background cache building for future requests. 
This change should be minimal, focus on refactoring existing files.

File search speed improvements (vibe-kanban)

---

frontend/src/lib/responsive-config.ts
frontend/src/pages/project-tasks.tsx

The reconnecting alert is sometimes to the left of the kanban instead of above it
frontend/src/pages/project-tasks.tsx

Update 'reconnecting' location (vibe-kanban)

---

frontend/src/components/dialogs/projects/ProjectFormDialog.tsx

Previously repo cards would overflow their container after the "Show more" button was pressed.

fix: repo card horizontal overflow

---

frontend/src/components/DiffCard.tsx
frontend/src/components/NormalizedConversation/EditDiffRenderer.tsx
frontend/src/components/diff-view-switch.tsx
frontend/src/components/tasks/TaskDetails/DiffTab.tsx
frontend/src/stores/useDiffViewStore.ts

UI switch for diff view split & inline modes

---

crates/server/src/bin/generate_types.rs
crates/server/src/routes/tasks.rs
frontend/package-lock.json
frontend/src/components/dialogs/tasks/TaskFormDialog.tsx
frontend/src/components/settings/ExecutorProfileSelector.tsx
frontend/src/components/settings/TaskSettings.tsx
frontend/src/components/settings/index.ts
frontend/src/components/tasks/Toolbar/CreateAttempt.tsx
frontend/src/hooks/useTaskMutations.ts
frontend/src/lib/api.ts
package-lock.json
shared/types.ts

When creating a new task, users have no way to select the base branch. We should add this.

Show branch selector in create new task (vibe-kanban)

---

frontend/src/components/dialogs/tasks/CreatePRDialog.tsx

When creating a PR, it should target the base branch of the task attempt, not main by default

Set PR branch (vibe-kanban)

---

frontend/src/components/dialogs/tasks/CreatePRDialog.tsx

Use generic branchselector in PR dialog

---

frontend/src/components/tasks/Toolbar/CurrentAttempt.tsx

Spinoff Task -> Create Subtask

Rename spinoff button (vibe-kanban)

---

frontend/src/components/DiffCard.tsx
frontend/src/components/diff/CommentWidgetLine.tsx
frontend/src/contexts/ReviewProvider.tsx
frontend/src/utils/string.ts

Currently review comments look like this:
```
**frontend/public/logs-worker.js** (Line 5)
> 12 hours rather than 7 days pls
```
But we should also add the line of code to the prompt, so it looks like this:
```
**frontend/public/logs-worker.js** (Line 5)
\`LINE OF CODE HERE\`
> 12 hours rather than 7 days pls
```
frontend/src/contexts/ReviewProvider.tsx

Review comments should contain line of code (vibe-kanban)

---

frontend/src/components/tasks/TaskDetails/ProcessesTab.tsx

Migrate the ProcessesTab to use @frontend/src/hooks/useExecutionProcesses.ts  instead of useAttemptExecution
@frontend/src/components/tasks/TaskDetails/ProcessesTab.tsx

Migrate the ProcessesTab (vibe-kanban)

---

frontend/src/components/DiffCard.tsx
frontend/src/components/diff/CommentWidgetLine.tsx
frontend/src/components/diff/ReviewCommentRenderer.tsx
frontend/src/contexts/ReviewProvider.tsx

frontend/src/components/diff/ReviewCommentRenderer.tsx
frontend/src/contexts/ReviewProvider.tsx
frontend/src/components/ui/file-search-textarea.tsx

Use file search when leaving a review comment (vibe-kanban)

---

crates/executors/src/executors/mod.rs
crates/server/src/routes/config.rs
frontend/src/components/NormalizedConversation/UserMessage.tsx
shared/types.ts

Disable Edit & Retry feature for agents that don't implement session forking

---

frontend/src/components/logs/VirtualizedList.tsx

Move ItemContent outside component to avoid re-render

Improve Virtuoso performance

---

frontend/src/hooks/useConversationHistory.ts

Hide deleted processes in the log view

---

crates/executors/src/executors/codex/session.rs

fix OS issue `Failed to create forked rollout ... File name too long (os error 36)`

fix: codex session forking regression

---

crates/utils/src/stream_ext.rs

truncate the middle rather than the end

---

crates/services/src/services/github_service.rs

If it's the error that base branch doesn't exist, and the base isn't main, please update the error message to say something like "did you mean to use main as your base branch instead?"

Update failed to create PR error message (vibe-kanban)

---

crates/db/.sqlx/query-eed92030636e8c992067e3cf899b01f06849a71230a0d2a58963dc0d2930244f.json
crates/db/src/models/project.rs
crates/deployment/src/lib.rs
crates/server/src/routes/config.rs
crates/server/src/routes/filesystem.rs
crates/services/src/services/filesystem.rs

When a user has no projects setup, this is the case for new users, instead of making them pick, already setup the three most recent repos. frontend/src/components/projects/github-repository-picker.tsx already has a way to fetch these.

Default project setup (vibe-kanban)

---

crates/services/src/services/config/mod.rs
crates/services/src/services/config/versions/mod.rs
crates/services/src/services/config/versions/v7.rs
frontend/src/components/theme-provider.tsx
frontend/src/utils/theme.ts
shared/types.ts

Remove all themes except for dark/light/system.
Adresses #802

Remove colour themes (vibe-kanban)

---

frontend/src/components/tasks/AttemptHeaderCard.tsx

`destructive` -> `console-error`

consistent diff colors

---

frontend/src/keyboard/useSemanticKey.ts

Regression introduced by https://github.com/BloopAI/vibe-kanban/pull/847

Fix shortcut infinite re-render

---

frontend/package.json
frontend/src/main.tsx
package.json

https://github.com/BloopAI/vibe-kanban-web-companion

Implement Vibe Kanban Web Companion

---

frontend/src/components/NormalizedConversation/PendingApprovalEntry.tsx
frontend/src/components/ui/circular-progress.tsx
frontend/src/hooks/useKeyboardShortcut.ts
frontend/src/keyboard/hooks.ts
frontend/src/keyboard/registry.ts
frontend/src/keyboard/types.ts
frontend/src/keyboard/useSemanticKey.ts

- `enter` to approve / `meta+enter` to submit a denial reason 
- styling tweaks
- restructured `PendingApproval` component

feat: keyboard shortcuts for approvals

---

crates/server/src/routes/task_attempts.rs
crates/services/src/services/git.rs

fix wrong ahead/behind commit info for remote branches

Fix wrong git status for remote branches

---

crates/executors/src/executors/acp/harness.rs

fix Gemini on windows

---

crates/local-deployment/src/container.rs

If you're working on a big feature there may be long periods of time where cleanup scripts fail, eg typescript errors, and this is totally fine. Currently having to open up the repo and manually commit as we were failing on cleanup script failure.

If cleanup script fails, commit anyway (vibe-kanban)

---

frontend/src/i18n/locales/es/common.json
frontend/src/i18n/locales/es/settings.json
scripts/check-i18n.sh

Extend the scripts/check-i18n.sh script to check that each translation file contains the exact same keys

Check i18n consistency (vibe-kanban)

---

crates/executors/Cargo.toml
crates/executors/src/executors/codex.rs
crates/executors/src/executors/codex/client.rs
crates/executors/src/executors/codex/jsonrpc.rs
crates/executors/src/executors/codex/normalize_logs.rs
crates/executors/src/executors/codex/session.rs
crates/executors/src/logs/mod.rs
crates/executors/src/logs/stderr_processor.rs
shared/schemas/codex.json
shared/types.ts

Use the new `app-server` protocol to interact with codex cli.

Upgrade Codex to the latest version

---

crates/server/src/routes/approvals.rs
crates/server/src/routes/projects.rs
crates/server/src/routes/task_attempts.rs
crates/server/src/routes/task_templates.rs
crates/server/src/routes/tasks.rs

We need more events to figure out what features users find and use and to spot others that go unused. Please include the following endpoints:
in crates/server/src/routes/task_attempts.rs
- start-dev-server
- rebase
- open-editor
- stop
- change-target-branch
- children
in crates/server/src/routes/task_templates.rs
- create-template
- update-template
in crates/server/src/routes/tasks.rs
- delete-task
in crates/server/src/routes/images.rs
- upload-image
in crates/server/src/routes/projects.rs
- open-editor
- / (delete_project)
in crates/server/src/routes/approvals.rs
- create
- respond

More events (vibe-kanban)

---

frontend/src/components/NormalizedConversation/PendingApprovalEntry.tsx
frontend/src/components/diff/CommentWidgetLine.tsx
frontend/src/components/diff/ReviewCommentRenderer.tsx
frontend/src/components/ui/file-search-textarea.tsx

- Autofocus approval feedback textbox
- Add filesearch to approval feedback textbox
- Fix autofocus for ReviewCommentsRenderer and CommentWidgetLine

File search in approval text box (vibe-kanban)
