- backend/.sqlx/query-ac5247c8d7fb86e4650c4b0eb9420031614c831b7b085083bac20c1af314c538.json
- backend/src/models/task_attempt.rs
- backend/src/services/git_service.rs
- frontend/src/components/tasks/BranchSelector.tsx
- frontend/src/components/tasks/TaskDetailsToolbar.tsx
- frontend/src/components/tasks/Toolbar/CreateAttempt.tsx
- frontend/src/components/tasks/Toolbar/CurrentAttempt.tsx
- frontend/src/lib/api.ts
The backend endpoint for rebasing should support changing the base branch. Next to the "BASE BRANCH" section in task details we should add a small icon which when clicked allows the user to choose a new base branch for the task attempt
frontend/src/components/tasks/TaskDetails
backend/src/routes/task_attempts.rs
> Rebase that changes base (vibe-kanban)

- README.md
- backend/src/routes/auth.rs
Enable devs to use their own GitHub OAuth app instead of the hardcoded Bloop AI client ID when building Vibe Kanban from source.
- Modified `backend/src/routes/auth.rs` to use option_env!("GITHUB_CLIENT_ID") instead of hardcoded client ID
- Follows the same pattern as the existing `POSTHOG_API_KEY` environment variable
- Falls back to the original Bloop AI client ID (`Ov23li9bxz3kKfPOIsGm`) if no environment variable is set
- updated `README.md` with a descriptive table of this setting and other settings
To build with your own GitHub OAuth app:
```bash
GITHUB_CLIENT_ID=your_client_id_here pnpm run build
```
> feat: Allow custom GitHub OAuth app client ID via environment variable

- backend/Cargo.toml
- backend/src/executor.rs
- backend/src/executors/claude.rs
- backend/src/executors/gemini.rs
- backend/src/executors/gemini/config.rs
- backend/src/executors/gemini/streaming.rs
- backend/src/main.rs
- backend/src/routes/mod.rs
- backend/src/routes/stream.rs
- backend/src/routes/task_attempts.rs
- frontend/package-lock.json
- frontend/package.json
- frontend/src/components/tasks/TaskDetails/LogsTab/NormalizedConversationViewer.tsx
- pnpm-lock.yaml
The main focus was on Gemini-CLI token streaming, which uses the standard JSON-Patch format to stream real-time updates to the frontend via SSE.
There is also a default database-backed SSE implementation which covers the remaining executors like Claude-code.
Should resolve #179.
Hopefully resolves #180.
> Streaming support for conversation history with SSE

- backend/src/models/task_attempt.rs
- frontend/src/components/tasks/TaskDetails/LogsTab.tsx
- shared/types.ts
- Display different messages depending on whether a `TaskAttempt` errored or was stopped.
> fix: distinguish between stopped and failed task attempts

- frontend/src/pages/project-tasks.tsx
When creating new tasks from a plan task the UI should navigate to the new task, need to refetch to get the newly created task.
> fix: improve task fetching logic when no tasks are loaded

- frontend/src/components/projects/project-form-fields.tsx
In the settings where you update cleanup script the copy currently reads:
This script will run after coding agent execution is complete. Use it for cleanup tasks like stopping processes, clearing caches, or other post-execution cleanup.
Please change this to have better examples like running linters, formatters and validations
> Update cleanup script copy (vibe-kanban)

- backend/src/models/task_attempt.rs
- backend/src/services/git_service.rs
When rebasing a task branch onto a different base branch, unintended commits appear if the old base branch is itself based on the new base branch. The current rebase includes all commits from the merge-base, not just the task-specific commits.
The issue is in `backend/src/services/git_service.rs:rebase_branch()` around lines 418-424. The current implementation uses a standard Git rebase that includes all commits between the task branch and the new base branch.
Replace the current rebase logic with a **smart rebase** that:
1. Identifies the actual old base branch from the database
2. Calculates commits unique to the task branch (not in either base)
3. Cherry-picks only those unique commits onto the new base
**File**: `backend/src/services/git_service.rs`
- Add `old_base_branch` parameter …
> Execute Plan: Rebase onto different branch update (vibe-kanban)

- backend/src/routes/stream.rs
When a client reconnects with `since_batch_id`, non-Gemini executors must iterate through the polling loop **one entry at a time** to catch up to the current state. This is extremely slow for processes with many entries.
**Lines 72-73**: The loop always calls `interval.tick().await` before processing, meaning:
- If there are 500 entries to catch up on, it takes 500 × poll_interval (50+ seconds at 100ms)
- Each iteration processes only 1 entry (`last_entry_count += 1` at line 182)
- No fast-path for historical data that already exists
**Key Insight**: Historical entries don't need polling - they already exist in the normalized logs.
**Implementation Strategy:**
1. **Before entering the polling loop**: If `since_batch_id` is provided, immediately process all existing entries
2. **Fast batch …
> Execute Plan: Stream more patches to the FE (vibe-kanban)

- backend/migrations/20250720000000_add_cleanupscript_to_process_type_constraint.sql
This is a sneaky one, the previous approach was triggering ON DELETE CASCADE in other tables. This approach avoids that issue
> Fix migration

- backend/src/bin/generate_types.rs
- backend/src/executor.rs
- frontend/src/pages/McpServers.tsx
- shared/types.ts
Now we define a set of executors that support MCP Server configuration (`MCP_SUPPORTED_EXECUTORS`).
This allows us to exclude `Claude Code Plan`, which shares the same configuration as `Claude Code`.
> chore: define executors with MCP configuration

- crates/local-deployment/src/container.rs
- crates/services/src/services/container.rs
- crates/services/src/services/git.rs
Try to commit changes after successful `CodingAgent` or `CleanupScript` execution
> refactor: commit changes after successful execution

- frontend/src/components/tasks/Toolbar/CurrentAttempt.tsx
Updated the PR button text from "Open PR" to "View PR" when a pull request already exists, making it clearer that clicking will view the existing PR rather than create a new one. Also renamed the handler function from `handleCreatePRClick` to `handlePRButtonClick` to better reflect its dual purpose of creating or viewing PRs.
> rename PR button handler and update button text for clarity

- frontend/src/components/tasks/TaskFormDialog.tsx
When creating a task, pressing escape or clicking outside the dialog will close it, discarding all of the content. When the title or description have content, there should be a warning about this instead.
> Frontend: Fix esc/click discarding existing input (vibe-kanban)

- crates/executors/src/logs/utils/entry_index.rs
- crates/local-deployment/src/container.rs
- crates/services/src/services/container.rs
- crates/services/src/services/git.rs
- frontend/src/components/projects/project-form-fields.tsx
- frontend/src/utils/script-placeholders.ts
Please plan how to skip running the cleanup script if there are no changes made during coding agent execution.
> Skip running cleanup script if no changes (vibe-kanban)

- crates/local-deployment/src/container.rs
I get the error:
```
thread 'tokio-runtime-worker' panicked at crates/local-deployment/src/container.rs:
byte index 100 is not a char boundary; it is inside '✨' (bytes 98..101) of `## ✅ **Project Complete!**
```
For the code:
```
/// Update the executor session summary with the final assistant message
async fn update_executor_session_summary(&self, exec_id: &Uuid) -> Result<(), anyhow::Error> {
// Check if there's an executor session for this execution process
let session =
ExecutorSession::find_by_execution_process_id(&self.db.pool, *exec_id).await?;
if let Some(session) = session {
// Only update if summary is not already set
if session.summary.is_none() {
if let Some(summary) = self.extract_last_assistant_message(exec_id) {
tracing::debug!(
"Updating executor session summary for …
```
> Summary error (vibe-kanban)

- frontend/src/components/DiffCard.tsx
Choose an appropriate icon from lucide, replace the weird custom SVG
> Replace the 'open in IDE' icon with lucide (vibe-kanban)

- .dockerignore
- Dockerfile
This pull request improves the container builds.
- Refactored the Dockerfile
- Build the application as part of the Docker build, rather than depending on the external host having to build the frontend/backend, then copying those into an image which does not contain the build environment
- Use a multi-stage build for smaller and more secure images
- Fix the broken entrypoint cmd
- Updated NodeJS base image from the old, unmaintained version v18 to the current stable v24
- Run as a non-privileged user
- Added `.dockerignore`
> Refactor docker builds

- crates/local-deployment/src/container.rs
- frontend/src/pages/project-tasks.tsx
Aligns VK branch names with common branch naming convention `author/branch-name`.
Quick fix for https://github.com/BloopAI/vibe-kanban/issues/632
> feat: `vk/xxxx-xxxx-xxxx` branch naming convention

- frontend/src/components/OnboardingDialog.tsx
- frontend/src/components/projects/project-form-fields.tsx
- frontend/src/components/tasks/AttemptHeaderCard.tsx
- frontend/src/components/tasks/TaskDetails/ProcessesTab.tsx
- frontend/src/components/tasks/Toolbar/CurrentAttempt.tsx
- frontend/src/pages/settings/AgentSettings.tsx
- frontend/src/pages/settings/GeneralSettings.tsx
- `agent` over `executor`
- `configuration` over `profile`
> chore: make agent terminology more consistent

- frontend/src/components/dialogs/global/ReleaseNotesDialog.tsx
Currently, the dialogue overflows the page size and requires scrolling to get to the bottom button. This UI fix makes it fit nicely into the page window.
Before:
After:
> Small fix: improve Release notes dialog

- frontend/src/App.tsx
- frontend/src/components/ui/dropdown-menu.tsx
- frontend/src/pages/settings/AgentSettings.tsx
- frontend/src/pages/settings/GeneralSettings.tsx
- frontend/src/pages/settings/McpSettings.tsx
- Made the Save button look the same on all settings pages
- Fixed double scroll on settings pages by making general app container flex (checked on projects and tasks pages and seems to be fine, but possibly needs another check)
- Fixed separator in navbar menu not showing up due to same colour as background
> Minor UI fixes for settings page

- crates/executors/src/executors/claude.rs
User can sometimes end up using their anthropic key inadvertently, rather than their Anthropic subscription
> Print warning if not using anthropic subscription

- frontend/src/components/tasks/TaskFollowUpSection.tsx
Before: Send keyboard shortcut ALWAYS starts follow-up, even when an attempt is running.
Now: Send keyboard shortcut queues the follow-up if an attempt is running, same behaviour as the send button
> fix: send keyboard shortcut should queue when attempt is running

- frontend/src/hooks/useConversationHistory.ts
This PR fixes an error that occurs when sending a message in the chat while a dev server is running.
Fixes #723
When users have a dev server running and try to send a message in the task chat, the application crashes with:
```
Error: More than one running execution process found
```
This happens because the `getRunningExecutionProcesses` function counts both the dev server process and the agent process as running processes, triggering the error when it finds more than one.
Modified the `getRunningExecutionProcesses` function in `useConversationHistory.ts` to exclude dev server processes from the count by filtering out processes where `run_reason === 'devserver'`.
The function now only considers actual agent processes when checking for multiple running processes, allowing the dev server to …
> Fix: Exclude dev server from running process check

- .github/workflows/pre-release.yml
> GitHub action pre-release shouldn't depend on package lock (vibe-kanban)

- README.md
- frontend/src/components/layout/navbar.tsx
Update all docs links that currently point to vibekanban.com instead of vibekanban.com/docs
> Use correct docs link (vibe-kanban)

- docs/configuration-customisation/agent-configurations.mdx
- docs/configuration-customisation/global-settings.mdx
- docs/index.mdx
`/user-guide` is no longer a valid folder in docs.
docs/index.mdx
docs/configuration-customisation/global-settings.mdx 
docs/configuration-customisation/agent-configurations.mdx
> docs: remove all references to /user-guide (vibe-kanban)

- crates/db/src/models/task.rs
- crates/server/src/mcp/task_server.rs
- crates/server/src/routes/tasks.rs
- crates/services/src/services/events.rs
- shared/types.ts
TaskWithAttemptStatus non-Task fields do not update correctly.
This causes an issue where tasks do not correctly show running/error state on the kanban board.
> Refactor TaskWithAttemptStatus (vibe-kanban)

- frontend/src/components/ui/shadcn-io/kanban/index.tsx
- frontend/src/pages/project-tasks.tsx
- package.json
Previously, if a card in the Kanban board was dragged to the far right edge of the screen, it would continue scrolling.
With this change, we introduce a variant of the `restrictToFirstScrollableAncestor` dnd-kit modifier (https://docs.dndkit.com/api-documentation/modifiers#restricttofirstscrollableancestor).
This modifier additionally limits the x delta of the dragged card by comparing the right edge of the card to the right edge of the scrollable ancestor and ensuring that it is at least 16 units.
> Fix/kanban infinite horizontal dragging (2)

- crates/db/Cargo.toml
- crates/local-deployment/Cargo.toml
- crates/server/Cargo.toml
- crates/services/Cargo.toml
- crates/services/src/services/events.rs
Utilise the `sqlite-preupdate-hook` feature of SQLX to set a pre update hook for task deletion. This works around the fact that the post update hook only gets rowid, and if the task has been deleted then we can't lookup the ID to update the JSON meaning we'd fail to push delete patches for any entities in this file.
Original issue:
When a task is deleted, the DB hook runs this code: https://github.com/BloopAI/vibe-kanban/blob/3a68435f2a0c1eeebaa2ba729a8486e4d06473ea/crates/services/src/services/events.rs#L261-L270
But at this point, the task isn't in the DB so project_id and task_id  in the RecordTypes::DeletedTask struct are None and thus the pattern match responsible for generating the remove JSON patch doesn't fire.
https://github.com/BloopAI/vibe-kanban/blob/3a68435f2a0c1eeebaa2ba729a8 …
> Debug delete issue / refactor event deletion (vibe-kanban)

- frontend/src/components/tasks/TaskDetailsPanel.tsx
I have noticed that sometimes when I navigate from one task attempt to another, the todos from the previous attempt can still be displayed
frontend/src/components/tasks/TodoPanel.tsx
> Todos do not update when the user changes task attempt (vibe-kanban)

- crates/executors/src/executors/claude.rs
2.0.49 is in not valid. 1.0.49 is. this is likely a minor typo
> fix claude code rotuer version

- frontend/src/components/tasks/TaskDetailsToolbar.tsx
- frontend/src/components/tasks/Toolbar/GitOperations.tsx
Currently we hide frontend/src/components/tasks/Toolbar/GitOperations.tsx when branchstatus fails. Change this to only hide merge/pr/rebase buttons and keep the rest.
> Keep git panel when branchstatus fails (vibe-kanban)

- frontend/src/components/ui/auto-expanding-textarea.tsx
- frontend/src/components/ui/input.tsx
This fix issue #919 where pressing Enter during IME (Input Method Editor) composition incorrectly triggers form submission in task title and description fields.
Changes:
- Add isComposing check to Input component's Enter key handler
- Add isComposing check to AutoExpandingTextarea component's Enter key handler
This ensures that Enter key during IME composition (e.g., Japanese, Chinese, Korean input) only confirms the text conversion without accidentally submitting the form.
Fixes #919
> Fix: Prevent form submission during IME composition

- frontend/src/components/ui/markdown-renderer.tsx
Fix React error #284 in the markdown-renderer component by preventing invalid ref attributes from being passed to DOM elements. The issue occurs because markdown-to-jsx parses raw HTML in user content and forwards all attributes (including invalid ref values) to the override components, which then spread these props onto DOM elements. Create a safeDomProps helper function that strips React-reserved props (ref, key, dangerouslySetInnerHTML) and optionally event handlers before spreading props to DOM nodes. Apply this helper to all markdown overrides in the component (strong, em, p, h1, h2, h3, ul, ol, li, and the InlineCodeOverride function) by replacing {...props} with {...safeDomProps(props)}. While you're in the file, also fix the typo on line 155 where text-baseleading-tight should be …
> Markdown renderer bug (vibe-kanban)

- docs/configuration-customisation/keyboard-shortcuts.mdx
- frontend/src/keyboard/registry.ts
Arrow keys and enter conflict with too many browser defaults, eg submit or navigating a dropdown.
While technically solvable, usability isn't great if you think you have something selected but it's not, and it's too easy to accidentally navigate to a different task while say trying to navigate a dropdown of branches.
This leaves hjkl and CMD+enter
> Tweak keyboard shortcuts, arrow keys + enter (vibe-kanban)

- frontend/src/components/dialogs/tasks/TaskFormDialog.tsx
- frontend/src/components/diff/CommentWidgetLine.tsx
- frontend/src/components/tasks/TaskFollowUpSection.tsx
- frontend/src/components/tasks/follow-up/FollowUpEditorCard.tsx
- frontend/src/components/ui/auto-expanding-textarea.tsx
- frontend/src/components/ui/file-search-textarea.tsx
- frontend/src/hooks/useKeyboardShortcut.ts
- frontend/src/keyboard/hooks.ts
- frontend/src/keyboard/registry.ts
Add a shortcut to cycle between agent configurations (previously called profile variants) when typing a follow up. Should be active when the user is editing the follow-up text box.
User shift tab to trigger the shortcut.
> Add variant/config cycle keyboard shortcut (vibe-kanban)

- crates/executors/src/executors/claude.rs
- crates/executors/src/executors/hooks/confirm.py
- crates/executors/src/logs/mod.rs
- frontend/src/components/NormalizedConversation/DisplayConversationEntry.tsx
- frontend/src/i18n/locales/en/common.json
- frontend/src/i18n/locales/es/common.json
- frontend/src/i18n/locales/ja/common.json
- shared/types.ts
When interacting with an approval and the users chooses to deny the request with feedback, the feedback text should be displayed as a user message. Currently it's not displayed
> No user deny messages in history (vibe-kanban)

- frontend/src/components/tasks/Toolbar/GitOperations.tsx
The PR link in frontend/src/components/tasks/Toolbar/GitOperations.tsx is hard to find, add a blue version of the external link icon. The icon is e.g. already used for the open in IDE button.
> Add blue external link icon to PR link (vibe-kanban)

- frontend/src/components/NormalizedConversation/EditDiffRenderer.tsx
We should always display these diffs in `inline` view
> feat: Remove the `inline` or `split` diff view selector from diffs in the conversation logs (vibe-kanban)

- crates/local-deployment/src/container.rs
- crates/services/src/services/diff_stream.rs
- crates/services/src/services/filesystem_watcher.rs
- crates/services/src/services/mod.rs
- Fix initial diff not being sent before filesystem watcher is ready, causing slow diffs
- Refactor live diffs
- Improve filesystem watcher `.gitignore` discovery performance
> Live Diff Service Refactor (vibe-kanban)
